version: '3'

services:
  impali-db:
    image: postgres:12-alpine
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Password01

  impali-webpacker:
    build: . 
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    command: ./bin/webpack-dev-server
    volumes:
      - .:/impali 
      - bundler_gems:/usr/local/bundle 
    ports:
      - "3035:3035"
  
  impali-web:
    build: . 
    tty: true 
    stdin_open: true 
    volumes:
      - .:/impali 
      - bundler_gems:/usr/local/bundle 
    ports:
      - "3000:3000"
    depends_on:
      - impali-db
    command: 
      - /bin/sh 
      - -c 
      - |
        # Remove a potentially pre-existing server.pid for Rails.
        rm -f /impali/tmp/pids/server.pid
        # Start server
        bundle exec rails server -b 0.0.0.0 -p 3000
    environment:
      RACK_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: impali-webpacker

volumes:
  bundler_gems:
  database: