require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/classroom_subjects", type: :request do
  
  # ClassroomSubject. As you add validations to ClassroomSubject, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ClassroomSubject.create! valid_attributes
      get classroom_subjects_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      classroom_subject = ClassroomSubject.create! valid_attributes
      get classroom_subject_url(classroom_subject)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_classroom_subject_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      classroom_subject = ClassroomSubject.create! valid_attributes
      get edit_classroom_subject_url(classroom_subject)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ClassroomSubject" do
        expect {
          post classroom_subjects_url, params: { classroom_subject: valid_attributes }
        }.to change(ClassroomSubject, :count).by(1)
      end

      it "redirects to the created classroom_subject" do
        post classroom_subjects_url, params: { classroom_subject: valid_attributes }
        expect(response).to redirect_to(classroom_subject_url(ClassroomSubject.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ClassroomSubject" do
        expect {
          post classroom_subjects_url, params: { classroom_subject: invalid_attributes }
        }.to change(ClassroomSubject, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post classroom_subjects_url, params: { classroom_subject: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested classroom_subject" do
        classroom_subject = ClassroomSubject.create! valid_attributes
        patch classroom_subject_url(classroom_subject), params: { classroom_subject: new_attributes }
        classroom_subject.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the classroom_subject" do
        classroom_subject = ClassroomSubject.create! valid_attributes
        patch classroom_subject_url(classroom_subject), params: { classroom_subject: new_attributes }
        classroom_subject.reload
        expect(response).to redirect_to(classroom_subject_url(classroom_subject))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        classroom_subject = ClassroomSubject.create! valid_attributes
        patch classroom_subject_url(classroom_subject), params: { classroom_subject: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested classroom_subject" do
      classroom_subject = ClassroomSubject.create! valid_attributes
      expect {
        delete classroom_subject_url(classroom_subject)
      }.to change(ClassroomSubject, :count).by(-1)
    end

    it "redirects to the classroom_subjects list" do
      classroom_subject = ClassroomSubject.create! valid_attributes
      delete classroom_subject_url(classroom_subject)
      expect(response).to redirect_to(classroom_subjects_url)
    end
  end
end
