require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/online_applications", type: :request do
  
  # OnlineApplication. As you add validations to OnlineApplication, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      OnlineApplication.create! valid_attributes
      get online_applications_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      online_application = OnlineApplication.create! valid_attributes
      get online_application_url(online_application)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_online_application_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      online_application = OnlineApplication.create! valid_attributes
      get edit_online_application_url(online_application)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OnlineApplication" do
        expect {
          post online_applications_url, params: { online_application: valid_attributes }
        }.to change(OnlineApplication, :count).by(1)
      end

      it "redirects to the created online_application" do
        post online_applications_url, params: { online_application: valid_attributes }
        expect(response).to redirect_to(online_application_url(OnlineApplication.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OnlineApplication" do
        expect {
          post online_applications_url, params: { online_application: invalid_attributes }
        }.to change(OnlineApplication, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post online_applications_url, params: { online_application: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested online_application" do
        online_application = OnlineApplication.create! valid_attributes
        patch online_application_url(online_application), params: { online_application: new_attributes }
        online_application.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the online_application" do
        online_application = OnlineApplication.create! valid_attributes
        patch online_application_url(online_application), params: { online_application: new_attributes }
        online_application.reload
        expect(response).to redirect_to(online_application_url(online_application))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        online_application = OnlineApplication.create! valid_attributes
        patch online_application_url(online_application), params: { online_application: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested online_application" do
      online_application = OnlineApplication.create! valid_attributes
      expect {
        delete online_application_url(online_application)
      }.to change(OnlineApplication, :count).by(-1)
    end

    it "redirects to the online_applications list" do
      online_application = OnlineApplication.create! valid_attributes
      delete online_application_url(online_application)
      expect(response).to redirect_to(online_applications_url)
    end
  end
end
