require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/private_threads", type: :request do
  
  # PrivateThread. As you add validations to PrivateThread, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PrivateThread.create! valid_attributes
      get private_threads_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      private_thread = PrivateThread.create! valid_attributes
      get private_thread_url(private_thread)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_private_thread_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      private_thread = PrivateThread.create! valid_attributes
      get edit_private_thread_url(private_thread)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PrivateThread" do
        expect {
          post private_threads_url, params: { private_thread: valid_attributes }
        }.to change(PrivateThread, :count).by(1)
      end

      it "redirects to the created private_thread" do
        post private_threads_url, params: { private_thread: valid_attributes }
        expect(response).to redirect_to(private_thread_url(PrivateThread.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PrivateThread" do
        expect {
          post private_threads_url, params: { private_thread: invalid_attributes }
        }.to change(PrivateThread, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post private_threads_url, params: { private_thread: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested private_thread" do
        private_thread = PrivateThread.create! valid_attributes
        patch private_thread_url(private_thread), params: { private_thread: new_attributes }
        private_thread.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the private_thread" do
        private_thread = PrivateThread.create! valid_attributes
        patch private_thread_url(private_thread), params: { private_thread: new_attributes }
        private_thread.reload
        expect(response).to redirect_to(private_thread_url(private_thread))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        private_thread = PrivateThread.create! valid_attributes
        patch private_thread_url(private_thread), params: { private_thread: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested private_thread" do
      private_thread = PrivateThread.create! valid_attributes
      expect {
        delete private_thread_url(private_thread)
      }.to change(PrivateThread, :count).by(-1)
    end

    it "redirects to the private_threads list" do
      private_thread = PrivateThread.create! valid_attributes
      delete private_thread_url(private_thread)
      expect(response).to redirect_to(private_threads_url)
    end
  end
end
