require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/report_comments", type: :request do
  
  # ReportComment. As you add validations to ReportComment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ReportComment.create! valid_attributes
      get report_comments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      report_comment = ReportComment.create! valid_attributes
      get report_comment_url(report_comment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_report_comment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      report_comment = ReportComment.create! valid_attributes
      get edit_report_comment_url(report_comment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ReportComment" do
        expect {
          post report_comments_url, params: { report_comment: valid_attributes }
        }.to change(ReportComment, :count).by(1)
      end

      it "redirects to the created report_comment" do
        post report_comments_url, params: { report_comment: valid_attributes }
        expect(response).to redirect_to(report_comment_url(ReportComment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ReportComment" do
        expect {
          post report_comments_url, params: { report_comment: invalid_attributes }
        }.to change(ReportComment, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post report_comments_url, params: { report_comment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested report_comment" do
        report_comment = ReportComment.create! valid_attributes
        patch report_comment_url(report_comment), params: { report_comment: new_attributes }
        report_comment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the report_comment" do
        report_comment = ReportComment.create! valid_attributes
        patch report_comment_url(report_comment), params: { report_comment: new_attributes }
        report_comment.reload
        expect(response).to redirect_to(report_comment_url(report_comment))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        report_comment = ReportComment.create! valid_attributes
        patch report_comment_url(report_comment), params: { report_comment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested report_comment" do
      report_comment = ReportComment.create! valid_attributes
      expect {
        delete report_comment_url(report_comment)
      }.to change(ReportComment, :count).by(-1)
    end

    it "redirects to the report_comments list" do
      report_comment = ReportComment.create! valid_attributes
      delete report_comment_url(report_comment)
      expect(response).to redirect_to(report_comments_url)
    end
  end
end
