require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/student_attendances", type: :request do
  
  # StudentAttendance. As you add validations to StudentAttendance, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      StudentAttendance.create! valid_attributes
      get student_attendances_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      student_attendance = StudentAttendance.create! valid_attributes
      get student_attendance_url(student_attendance)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_student_attendance_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      student_attendance = StudentAttendance.create! valid_attributes
      get edit_student_attendance_url(student_attendance)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new StudentAttendance" do
        expect {
          post student_attendances_url, params: { student_attendance: valid_attributes }
        }.to change(StudentAttendance, :count).by(1)
      end

      it "redirects to the created student_attendance" do
        post student_attendances_url, params: { student_attendance: valid_attributes }
        expect(response).to redirect_to(student_attendance_url(StudentAttendance.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new StudentAttendance" do
        expect {
          post student_attendances_url, params: { student_attendance: invalid_attributes }
        }.to change(StudentAttendance, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post student_attendances_url, params: { student_attendance: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested student_attendance" do
        student_attendance = StudentAttendance.create! valid_attributes
        patch student_attendance_url(student_attendance), params: { student_attendance: new_attributes }
        student_attendance.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the student_attendance" do
        student_attendance = StudentAttendance.create! valid_attributes
        patch student_attendance_url(student_attendance), params: { student_attendance: new_attributes }
        student_attendance.reload
        expect(response).to redirect_to(student_attendance_url(student_attendance))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        student_attendance = StudentAttendance.create! valid_attributes
        patch student_attendance_url(student_attendance), params: { student_attendance: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested student_attendance" do
      student_attendance = StudentAttendance.create! valid_attributes
      expect {
        delete student_attendance_url(student_attendance)
      }.to change(StudentAttendance, :count).by(-1)
    end

    it "redirects to the student_attendances list" do
      student_attendance = StudentAttendance.create! valid_attributes
      delete student_attendance_url(student_attendance)
      expect(response).to redirect_to(student_attendances_url)
    end
  end
end
